title: Snippity Snap - Personal URL Shortener for Santosh Ganjur
description: âœ‚ï¸ğŸ”— a Github-based short URLs that can be easily shared, tweeted, or emailed to friends.
logo: /assets/img/logo.png
show_downloads: true
google_analytics: G-CX4QSQ2ZVD
theme: jekyll-theme-hacker

permalink: /:slug/

plugins:
  - jekyll-redirect-from

#repository: hlaueriksson/jekyll-url-shortener
